root = "."
tmp_dir = "tmp/api"

[build]
  cmd = "go build -buildvcs=false -o ./tmp/api/main ./cmd/api"
  bin = "./tmp/api/main"
  include_ext = ["go", "sql", "graphqls"]
  exclude_dir = ["tmp", "frontend", "node_modules", "deploy", "migrations"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
